groups:
  - name: blackbox
    rules:
      - alert: BlackboxProbeFailed
        expr: last_over_time(probe_success[5m]) == 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} is unreachable"
          description: "{{ $labels.instance }} can't be reached with {{ $labels.job }}"
