keys:
  - &nixchad_blueberry age1262s3k5k32mk8cnm8p7v6nsyaaftjn3zyzlej5z5jqjqsy8kmctsvv9hjy
  - &server_blueberry age1jmxvlpum4c9amt337wu4y0n5r0pkvahwy9k5edukhx34m8sr3yust0nj9u
  - &nixchad_blackberry age17getl6w9f04feedks6vj56fzw5jddwh3lckjc92fl7q0stpy054qklk42z
  - &server_blackberry age1s07n4270r8mrpws0kyx0deq8uvq2huutqqrg6jzdhwk0t5mgaytsszd2gs
  - &nixchad_virtberry age1dmfw6s04vlxj92zpe703tnwg2tgj8xy9w9qtvcz5f9nq09lpm4fqk7fk5t
  - &server_virtberry age15y2s6mrfk332ftmq6a80vr5t9wwdhs2fgae9vxq94h9h7ftlegus3ela90
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *nixchad_blueberry
        - *server_blueberry
        - *nixchad_blackberry 
        - *server_blackberry
        - *nixchad_virtberry
        - *server_virtberry
  - path_regex: secrets/blueberry/[^/]+\.yaml$
    key_groups:
      - age:
        - *nixchad_blueberry 
        - *server_blueberry
  - path_regex: secrets/blackberry/[^/]+\.yaml$
    key_groups:
      - age:
        - *nixchad_blackberry 
        - *server_blackberry
  - path_regex: secrets/virtberry/[^/]+\.yaml$
    key_groups:
      - age:
        - *nixchad_virtberry 
        - *server_virtberry
  # Workaround for git diff: https://github.com/mozilla/sops/issues/884
  - path_regex: .*
