[devshell]
name = "devshell"
packages = [
  "sops",
  "just"
]

[[env]]
name = "DEVSHELL_NO_MOTD"
value = 1


[[commands]]
name = "nswitch"
command = "nixos-rebuild --use-remote-sudo --flake '.#' switch -v"

[[commands]]
name = "ntest"
command = "nixos-rebuild --use-remote-sudo --flake '.#' test -v"

[[commands]]
name = "nboot"
command = "nixos-rebuild --use-remote-sudo --flake '.#' boot -v"

[[commands]]
name = "ndry"
command = "nixos-rebuild --use-remote-sudo --flake '.#' dry-activate -v"

[[commands]]
name = "nvm"
command = "nixos-rebuild --use-remote-sudo --flake '.#' build-vm -v"

[[commands]]
name = "nvm-boot"
command = "nixos-rebuild --use-remote-sudo --flake '.#' build-vm-with-bootloader -v"

[[commands]]
name = "ngc"
command = "sudo nix-collect-garbage --delete-older-than 7d"

[[commands]]
name = "nupdate"
command = "nix flake update"

[[commands]]
name = "ndiff"
command = "nix profile diff-closures --profile /nix/var/nix/profiles/system | less"

[[commands]]
name = "npreview"
command = "nixos-rebuild --use-remote-sudo --flake '.#' build -v && nix store diff-closures /var/run/current-system ./result"
