password: ENC[AES256_GCM,data:enfxYKtI8OE0CbPN2G2UyocWSeVl8m/0Me11ModYnwzRlOtmVioaU2mdcVZ8tXxon1lKKlIMN+LQOpAqAitWfwqY5avlTobyEOBAWKdItgGfqtjzfxY6sOo0wkfG/wCavzjLxCTqaA7kYA==,iv:V2jO9/DtOrZEXI8d/vH2ytGa0CcTt1Tq09qZiAvY23s=,tag:TLc4PRyA/mPNr7OATEknTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17getl6w9f04feedks6vj56fzw5jddwh3lckjc92fl7q0stpy054qklk42z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa1NKcit4ckFLWmhwYzRS
            NEcrbVR3dU05djhLK1p5QTFDaDhiS1NIV2dRCjhhcG9Lb3JGQXZQaE1mYTY5VVNY
            d05Db2x4Q3oxanBBUThmQ0lnWDRtOEkKLS0tIE5BSXdrdjJZRVJtb2FPRWxpaVVY
            cmRHZ09DaWtRcGR4ZlE4S29PeEZGNlEKxJkZV+VH6mbt0hHOUIJz3PsuDeo0yZwT
            nAmI7wjlo9IQl899lcr7Evy9XO/VAykxATqP6TqXQ/cHnYGtI8lV7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s07n4270r8mrpws0kyx0deq8uvq2huutqqrg6jzdhwk0t5mgaytsszd2gs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQjJ4amlMdUkySE9ocDZL
            QS9Bd0xhc1pwOW5oREdZMWc0bDliR0ZkZFdnCksrWFJHRkpzUHQ2Y3duYkYra1Z6
            dmJDVUh6QkZYdE91OGtnQlYwTENvVWMKLS0tIEZaWi9NaUR3YktNbDU2Q0dtQTlP
            c0JCWmVOSi9qb0FRUGNQK3NnVzVxeFUKIxfpf/J63oysxab+//f4LomNSWCx8oo2
            0mG3d4mPhQssv49AdLWaJeem6WbKqmfzg6fCecURHM2ZcuCXc0mU3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-11T01:44:22Z"
    mac: ENC[AES256_GCM,data:CTYjK67SIXjqiTcLdNatKGcng8wjeE3GSMfryDoZ5xkRJ90md6OLeVpp19GEbbLCPnJ5GSHTZVbB9KEVVukj0UmCxITlKvRQyzKJmKO4DRaZSuaYz5VlGsvwWRrXu9tto0oa8kOTqLnvlT0PrOrKxpuxJYMFbNHB8woPxDj+bGU=,iv:R6GKFZ6T7Nj1WU2UlHYGdYdWbmY6FE/HPoxOj6qxe0U=,tag:FrzCLLDFTd2kiryNpqKOhg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
