{
 "title": "Main",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "nodename",
    "label": "nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU pressure",
   "type": "timeseries",
   "description": "Time a process spent waiting for a CPU",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU seconds"
    }
   ]
  },
  {
   "title": "IO pressure",
   "type": "timeseries",
   "description": "Time a process spent waiting for IO",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Stalled"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Memory pressure",
   "type": "timeseries",
   "description": "Time a process spent waiting for free memory",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Stalled"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"$nodename\",job=\"systemd-journal\",unit!=\"loki.service\"}[1m] |~ \"(?i)error\")) by (unit)"
    }
   ]
  },
  {
   "title": "Warnings per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"$nodename\",job=\"systemd-journal\",unit!=\"loki.service\"}[1m] |~ \"(?i)warn\")) by (unit)"
    }
   ]
  }
 ]
}