# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.initrd.luks.devices.crypt = {
    device = "/dev/disk/by-uuid/bf0a2a4f-09a3-4f55-ad09-5b6723137062";
    preLVM = true;
  };
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/859fe7e9-6eca-4516-86f7-4acd2bd1b60d";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/B0C4-C3C5";
      fsType = "vfat";
    };

  fileSystems."/home/nixchad" =
    {
      device = "/dev/disk/by-uuid/7d75f41c-48b4-4b83-b186-f04ed19dd2f7";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/persist" =
    {
      device = "/dev/disk/by-uuid/9dd6e11c-d563-4957-9af1-a41b83071d75";
      fsType = "ext4";
      options = [ "noatime" ];
      neededForBoot = true;
    };

  zramSwap.enable = true;
  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
