password: ENC[AES256_GCM,data:BS5uYpq5O5kIdudMSXYeaZkV6HMj+gxgOteLpInYy62VPMZcETMR9C2dZ1pqmlR2Pl9edom15zXch8PRWqKfxDazEOvx0GS5lmZlZpFlOVgxVXV6/oj9oX1WN3YGfwAYjbP54mnqprJWlQ==,iv:Ckt78/qacCeI7z+hAo/A3pPrqO1saxnNuHwy7ize1mM=,tag:xlsdNNlsi7giSgoI0hbEQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1262s3k5k32mk8cnm8p7v6nsyaaftjn3zyzlej5z5jqjqsy8kmctsvv9hjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Mlg0bmtUQzB5bFZ0U09I
            dDV1djlwK3ZTOEtoU1pZSmpwRmtPYXBDUW5FCml3U2Y0SStyeGZNdDN4ZE9LNWYx
            SjZxMUp1U0dXL0ZqaldPVjhYaUZ2VWcKLS0tIEdzeVM4ODQ3bldQNVMzMEY4cXRu
            NS9jdW5xYjhuNXFvVDhiWEFuSmJ0c3MKbFTRcfmSOuBKSeIuwguhNo8kqlU6tpfF
            GUt/+ccInqnpTtO8JbbIcgnvDFhd73sKY4+qoNgm70df8oni3CSxzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jmxvlpum4c9amt337wu4y0n5r0pkvahwy9k5edukhx34m8sr3yust0nj9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY2t3RElEUEJYMVdzNCtw
            WkxPRjBhMlpZNG9URDNkeWoxN0lSemZvNVZFCjN0R2RsUVJBMEdITEMzeUZidkhs
            cmF1YVJjby9lNTBROTNNbDB0TVk2c0kKLS0tICtucmdkQlhpUC90dGZOWWhQV1pz
            OFBsTTdySmxoM0l3cmhTMXFpTlVJS2cKJD50pk9u2AcH3ZZArSYf3NaMRSQToDfX
            RXJav7WWijlNSLujc7mVKBjBgg6VJ4C7JtTPoLj/o8kDw6okd3LHfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-10T12:06:54Z"
    mac: ENC[AES256_GCM,data:pVfr5Zt7wYcCEuGLrMBtapaRUzO8qNy0LRNFiiMf3b3RPRwPIyt4dPFTVQocas1Y/KK3tzKwhtMJhxkuTPDyWyBhsp9USEmREi6AfrVSFepiFhnzcdl2swo749qYHjzzAE18MitF1giJWaYZ9DqiVEAzD/5fC/eFhFHDcsBaix4=,iv:P2Wyu+9fXP0Qlnp3wzcLH1K11rtT9Ac4h0ixVOKc9qQ=,tag:jV1QH7qaoxDqknK4yn0/ew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
