[hosts.blackberry]
ipv4 = "100.109.194.31"
interface = "enp4s0"
syncthing.id = "S3S7WIB-2J2YK4E-VIKFG4K-FZ7N4OI-43RXU3D-T5FX3AD-PQCJPSX-LNQNRA5"
ssh-pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEQ77pbUwzNYJzu/vEg9MqtuLQmjgRtf5b4K+qsZ0o7v nixchad@blackberry"

[hosts.cloudberry]
ipv4 = "37.27.0.141"
interface = "eth0"
syncthing.id = "PTFQGBZ-ZJ7PPKR-EDO2NOZ-IHFWCY6-AO7CW3X-G7VVFBH-R7IEE6G-Y2KK3QJ"

[phones.pixel-4a]
ipv4 = "100.107.161.19"
syncthing.id = "74LQXWB-GVD5FVU-7CYZUFK-MNIIYA4-X3ZJCHR-VQM7UM7-HBNL4VM-PUNYTAW"

# NOT SUPPORTED BY TAILSCALE AT THE MOMENT
# lol
# [outside.sunny]
# ipv4 = ""
# syncthing.id = ""

[ci.github-action]
ssh-pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN8XLDGBt0tt28PfY7O10WZJV793SUU3veDLkufyMKh7 github-action"
