apiVersion: 1

groups: 
- orgId: 1
  name: blackbox
  folder: Refined
  interval: 10s
  rules:
  - uid: provisioned_uid_alert_icmp_v4
    title: ICMP v4
    condition: B
    data:
    - refId: A
      datasourceUid: provisioned_uid_prometheus
      model:
        expr: 'probe_success{job="icmp_v4"} - 1'
      relativeTimeRange:
        from: 600
        to: 0
    - refId: B
      datasourceUid: '-100'
      model:
        conditions:
        - evaluator:
            params:
            - 0
            type: lt
          operator:
            type: and
          query:
            params:
            - A
          reducer:
            type: last
          type: query
        datasource:
          type: __expr__
          uid: '-100'
        expression: A
        reducer: last
        refId: B
        type: reduce
    for: 1m
    noDataState: OK
    annotations:
      summary: Endpoint {{ $labels.instance }} is down
    labels:
      severity: critical

  - uid: provisioned_uid_alert_http_2xx_v4
    title: HTTP 2xx v4
    condition: B
    data:
    - refId: A
      datasourceUid: provisioned_uid_prometheus
      model:
        expr: 'probe_success{job="http_2xx_v4"} - 1'
      relativeTimeRange:
        from: 600
        to: 0
    - refId: B
      datasourceUid: '-100'
      model:
        conditions:
        - evaluator:
            params:
            - 0
            type: lt
          operator:
            type: and
          query:
            params:
            - A
          reducer:
            type: last
          type: query
        datasource:
          type: __expr__
          uid: '-100'
        expression: A
        reducer: last
        refId: B
        type: reduce
    for: 1m
    noDataState: OK
    annotations:
      summary: Endpoint {{ $labels.instance }} is down
    labels:
      severity: critical

  - uid: provisioned_uid_alert_icmp_v6
    title: ICMP v6
    condition: B
    data:
    - refId: A
      datasourceUid: provisioned_uid_prometheus
      model:
        expr: 'probe_success{job="icmp_v6"} - 1'
      relativeTimeRange:
        from: 600
        to: 0
    - refId: B
      datasourceUid: '-100'
      model:
        conditions:
        - evaluator:
            params:
            - 0
            type: lt
          operator:
            type: and
          query:
            params:
            - A
          reducer:
            type: last
          type: query
        datasource:
          type: __expr__
          uid: '-100'
        expression: A
        reducer: last
        refId: B
        type: reduce
    for: 1m
    noDataState: OK
    annotations:
      summary: Endpoint {{ $labels.instance }} is down
    labels:
      severity: critical

  - uid: provisioned_uid_alert_http_2xx_v6
    title: HTTP 2xx v6
    condition: B
    data:
    - refId: A
      datasourceUid: provisioned_uid_prometheus
      model:
        expr: 'probe_success{job="http_2xx_v6"} - 1'
      relativeTimeRange:
        from: 600
        to: 0
    - refId: B
      datasourceUid: '-100'
      model:
        conditions:
        - evaluator:
            params:
            - 0
            type: lt
          operator:
            type: and
          query:
            params:
            - A
          reducer:
            type: last
          type: query
        datasource:
          type: __expr__
          uid: '-100'
        expression: A
        reducer: last
        refId: B
        type: reduce
    for: 1m
    noDataState: OK
    annotations:
      summary: Endpoint {{ $labels.instance }} is down
    labels:
      severity: critical

deleteRules:
  - uid: provisioned_uid_alert_http_v4
