password: ENC[AES256_GCM,data:Glngj52/L2U53WiD1ESQPZlqejuZrzB7Q0MQcrONAlxb0P0ZOmvutKxKRh+ajCwjGHhZng7XkrSyPGUxX0uKPGZ7Z1MZznZjZd1Inqzq+bRTg+jxYSdY/DRxYfp5fHeoDrph6uFk3qmT6g==,iv:/hbRy4D80pKnZR27niJgO0gVyZvO3jOqozBtRDtcxGE=,tag:CWxCVLrByP+w9vCsw7XFUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmfw6s04vlxj92zpe703tnwg2tgj8xy9w9qtvcz5f9nq09lpm4fqk7fk5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQUdRTTJ4SW5MTUw5L1Jq
            bEJPcTdjWGx0Z3dwT21ueTBxVHM1dE85YlZnClE5ZHFVSTRIYVJYRnE1VS9ybTVY
            L1FmMVdqN05mNHJMOWtEclU4VWhDaVkKLS0tIDliRXh5WlhqR24rRlBFQmx6dEFx
            TkRzR213YkVacFRULzVYUjY3ZEVrNlUKXW1neJkziFuiQOj+cLJjfN/62FENK1zN
            uxlMhCq174M8nkhDz09WabSXr3pJmOlywx9XRTD8aBbtXcXUrbc2Zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15y2s6mrfk332ftmq6a80vr5t9wwdhs2fgae9vxq94h9h7ftlegus3ela90
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWDNhb0FBT0I1OXJoNmhG
            ZTZhaUwvR1RUb044SGppSjF4WCtMZU15RmdFCkoya2d6R2p2QjVrUzdmb2VpV2pz
            UDhTZnRrT1BSQzZGMTVkTGlBZ0VQREEKLS0tIE1yWmpRN1pabWwxUUZPTkJHcmQy
            b256TFBHaFhESWl0Mld0eDJPWWlLYXcKm3KMHOJ8vwXQ8mV/5v6nJCWjEMD6MQn5
            IqekSC2xU1sOQOxkT9/L0/IDE6NxpKInsatINiOLwIsiZMq6ZGfcgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T22:48:55Z"
    mac: ENC[AES256_GCM,data:M9ZGxeBMb5IJbSeKff+UotMbka2kX2CAzY6IuUn6Iwz+lnplkPOg7LtUVJM74r7D0WNSWzQeWhIyhEWOnKZVfg2YCZAcOVV8brOcJpOwBGVoHaqrBPQAkFpNVbA1ay2i8WWvZ9ck38pAxvdydMJL+akkJF6VMU/Tj4G/tg+FcBA=,iv:ir3lfNQbDY2D+VBWK1UStQd4ZLJSv5AMeCKr9A3+Nok=,tag:Z8Zgm81pTeZdodrmssPvDA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
