name: Deployment pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v17
      with:
        nix_conf: experimental-features = nix-command flakes
    - name: Run deploy-rs
      run: |
        nix develop -c deploy . --keep-result --remote-build -- -v
