name: Deployment pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Connect to Tailscale network
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_ed25519
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v17
      with:
        nix_conf: |
          experimental-features = nix-command flakes ca-derivations
          builders = ssh-ng://nixchad@blackberry.tail34ad.ts.net i686-linux,x86_64-linux - 12 1000 kvm,nixos-test,benchmark,big-parallel - -
          builders-use-substitutes = true
          extra-substituters = ssh-ng://nixchad@blackberry.tail34ad.ts.net
          trusted-substituters = ssh-ng://nixchad@blackberry.tail34ad.ts.net
          require-sigs = false
          max-jobs = 0
    - name: Run deploy-rs
      run: |
        nix run . -- --remote-build -- -v --impure
