name: Testing pipeline

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v17
      with:
        nix_conf: experimental-features = nix-command flakes ca-derivations
    - name: Run pre-commit hooks
      run: |
        nix flake check

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v17
      with:
        nix_conf: experimental-features = nix-command flakes ca-derivations
    - name: Connect to Tailscale network
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_ed25519
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Dry-run deploy-rs
      run: |
        nix develop -c deploy . --keep-result --remote-build --dry-activate -- -v
