name: Testing pipeline

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v17
      with:
        nix_conf: experimental-features = nix-command flakes
    - name: Dry-run deploy-rs
      run: |
        nix develop -c deploy . --keep-result --remote-build --dry-activate -- -v
