name: Validation pipeline

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v17
      with:
        nix_conf: experimental-features = nix-command flakes
    - name: Run pre-commit hooks
      run: |
        nix flake check
