urls: ENC[AES256_GCM,data:Nj6m0dw31HMIa7W3vq3qXpb0/cPAac5KoZxrwkb6Mn0lMrUVa0k0F+Hviv+A3+zK00oXnKK/4Qi91Krn4Lul3bYOfCpGfU4E/rhV+Phy+8M5qHr9anZ80OJy/dRwO7TmvQi3z1vH1s0FS3juOInVWBYPljzUZDhjRM3mzL1X59l1g7EY4M11YTP0IgQULB4vh2MovXIcgPC8OKB02DkR,iv:RpA/DCFlePghyq90PKZ6rtjlSjR5aBRYlvr57guiA+U=,tag:9+u2f68mRe7YhR52k5b5uQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1262s3k5k32mk8cnm8p7v6nsyaaftjn3zyzlej5z5jqjqsy8kmctsvv9hjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ3ZvM1lPSkJOSU9sZ3lV
            UUVuM2wxcTF3eEUwajA4QUxCNW9rZG9wdEJVCk1XWE9IRkJ4bjQyQ2RxUDFITFRp
            czBEYjk3dXV1NDhweTZydzdkRjJIQzgKLS0tIDI3MnBxWkliWnRZS3pqY2tZZnhz
            YUx3aEF4VWJUMk11U09YcEw2ejhuTmMKapgKcyyobcb/nE6pkwqIlTH0mtuFFbKu
            9qIIZmy0iVKWW2Ir2Ja+Y4wiaADzzUl+USf+CFRsuOeSKwGFfGxd7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jmxvlpum4c9amt337wu4y0n5r0pkvahwy9k5edukhx34m8sr3yust0nj9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTiszQjU2RkMzbWtWZlov
            MlhpVWx0MVNldlNsYTl5c1lVOEVVWDBnQWpzCms2RHdabVBGNzZZUkxyeDRsWU1u
            L2xobm9DU0REY2c2bTFkdWV1OWJIekUKLS0tIGVEZldDV3lNNEVRcU9rNVIzS3pQ
            VmEyb3lHcFNVMzZzbTV5ZlZtZkN3OWsKiwSmXu13zAxu1lNPWl8L/4T5o1Dp/ZlJ
            YS4c+wCcVLN5OnJpcZo0GDYt667WwSvjs+WzmTQgYlGbRoZFlw3GQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-06T09:18:35Z"
    mac: ENC[AES256_GCM,data:Bkhg4ZH0Kt4bm8ZWMZd6tRxEC8loJZavUtO+sA0igDb4K5oqCyb3MhVGk1SQqH63Sz5yZdw96x/QgNcF/MQy1SQbO2zyKkDtNKZCWasdfu6/07fGOGwjNq7HdBlisJYnCOK2aXYuHjm7M4wtKYFmJbQZiRmpRvsCA+PLcRM9mcw=,iv:jj1VydeFo5jdji72/MtNl/nzRFg+mKMHrRkOPg6UyXw=,tag:gC83nUecluzTfF9aHXkwPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
